Repository AEnguerrand/cpp_zia, pull requests merged in 2018-02, with the labels that each got.

#16 Json configuration parser
  CMakeLists.txt
  conf/config.json
  lib/json.hpp
  src/Parser/ParserJson.cpp
  src/Parser/ParserJson.hh
  src/Parser/ParserJsonException.hpp
Labels: feat

#17 Process http (Base)
  SrcModules/Network/src/Network.cpp
  src/ModuleLoader/ModuleLoader.cpp
  src/ModuleLoader/ModuleLoader.hh
  src/Parser/Parser.cpp
  src/Parser/Parser.hh
  src/Process/Process.cpp
  src/Process/Process.hh
  src/zia.cpp
  src/zia.hh
Labels: feat

#18 Module network (Add basic test of "Hello World")
  .travis.yml
  CMakeLists.txt
  SrcModules/Network/src/Buffer.cpp
  SrcModules/Network/src/Buffer.hh
  SrcModules/Network/src/Errors.hpp
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Network.hh
  SrcModules/Network/src/Select.cpp
  SrcModules/Network/src/Select.hh
  SrcModules/Network/src/Socket.cpp
  SrcModules/Network/src/Socket.hh
  src/Parser/Parser.cpp
  src/Parser/Parser.hh
  src/zia.cpp
Labels: feat

#20 Units tests (Init and CodeCov)
  .travis.yml
  CMakeLists.txt
  CMakeLists.txt.in
  get_code_cov.sh
  tests/ParserTests.cpp
Labels: units tests

#21 ReadmeAddBadgeCodeCov(doc): Add badge for CodeCov
  README.md
Labels: enhancement

#22 Test hello world (Add hello world in Process)
  CMakeLists.txt
  SrcModules/Network/src/Buffer.cpp
  SrcModules/Network/src/Buffer.hh
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Network.hh
  SrcModules/Network/src/Select.cpp
  SrcModules/Network/src/Select.hh
  src/ModuleLoader/ModuleLoader.cpp
  src/Parser/Parser.cpp
  src/Parser/Parser.hh
  src/Process/Process.cpp
  src/Process/Process.hh
  src/zia.cpp
  src/zia.hh
  tests/ParserTests.cpp
Labels: feat

#23 Http parser
  .gitignore
  src/HttpParser/HttpParser.cpp
  src/HttpParser/HttpParser.hh
  src/HttpParser/HttpParserException.hpp
  src/HttpParser/Transform.hpp
Labels: feat

#28 Units test fix and add basics test for HttpParser
  .gitignore
  .travis.yml
  CMakeLists.txt
  configure.sh
  get_code_cov.sh
  tests/HttpParserTests.cpp
  tests/ParserTests.cpp
Labels: units tests

#29 coverageCodecov(fix): remove dir for coverage
  get_code_cov.sh
Labels: units tests

#31 Process / Send network async
  SrcModules/Network/src/Buffer.cpp
  src/Parser/Parser.cpp
  src/Parser/Parser.hh
Labels: feat

#32 Fix process async
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Network.hh
  SrcModules/Network/src/Select.cpp
  SrcModules/Network/src/Select.hh
  SrcModules/Network/src/Socket.cpp
  SrcModules/Network/src/Socket.hh
  src/Parser/Parser.cpp
  src/Parser/Parser.hh
  src/zia.cpp
Labels: feat

#34 Response to raw
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Select.cpp
  src/HttpParser/HttpParser.cpp
  src/HttpParser/HttpParser.hh
  src/Parser/Parser.cpp
  src/Process/Process.cpp
Labels: feat

#37 Module php - Init
  .gitignore
  CMakeLists.txt
  SrcModules/Network/src/Buffer.cpp
  SrcModules/Network/src/Select.cpp
  SrcModules/Php/CMakeLists.txt
  SrcModules/Php/src/Module.cpp
  SrcModules/Php/src/Module.hpp
  src/ModuleLoader/ModuleLoader.cpp
  src/Process/Process.cpp
Labels: feat

#40 conf_implementation(feat): Implementation of configuration parser done
  conf/config.json
  src/Parser/ParserJson.cpp
  src/Parser/ParserJson.hh
  src/Parser/ParserJsonException.hpp
  src/zia.cpp
  src/zia.hh
Labels: feat

#41 Module router - File directory base / File display only HTML / File 404
  CMakeLists.txt
  SrcModules/Network/src/Buffer.cpp
  SrcModules/Network/src/Select.cpp
  SrcModules/Router/CMakeLists.txt
  SrcModules/Router/src/Module.cpp
  SrcModules/Router/src/Module.hpp
  SrcModules/Router/src/Router.cpp
  SrcModules/Router/src/Router.hh
  src/Process/Process.cpp
Labels: feat

#42 Module router
  SrcModules/Router/src/Router.cpp
Labels: feat

#46 loadModule(feat): add fct to add and delete module from loader
  src/ModuleLoader/ModuleLoader.cpp
  src/ModuleLoader/ModuleLoader.hh
  src/zia.cpp
  src/zia.hh
Labels: feat

#48 Network request
  .gitignore
  SrcModules/Network/src/Buffer.cpp
  SrcModules/Network/src/Buffer.hh
  SrcModules/Network/src/HttpParser/HttpParser.cpp
  SrcModules/Network/src/HttpParser/HttpParser.hh
  SrcModules/Network/src/HttpParser/HttpParserException.hpp
  SrcModules/Network/src/HttpParser/Transform.hpp
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Select.cpp
  SrcModules/Network/src/Socket.cpp
  src/ModuleLoader/ModuleLoader.hh
  src/Parser/Parser.cpp
  src/zia.cpp
Labels: feat

#49 Htp parser check response validity
  src/HttpParser/HttpParser.cpp
  src/HttpParser/HttpParser.hh
  src/ModuleLoader/ModuleLoader.cpp
Labels: enhancement

#50 Siege integration with Travis CI
  .travis.yml
  src/HttpParser/HttpParser.cpp
  src/zia.cpp
  src/zia.hh
Labels: enhancement, units tests

#52 If no response is generate, internal server error is return
  src/Parser/Parser.cpp
  src/Parser/Parser.hh
Labels: bug

#54 Rework zia core
  src/Console/Console.cpp
  src/Console/Console.hh
  src/ModuleLoader/ModuleLoader.cpp
  src/ModuleLoader/ModuleLoader.hh
  src/main.cpp
  src/zia.cpp
  src/zia.hh
Labels: feat

#56 Hotfix (Siege testing is broken)
  .travis.yml
Labels: bug

#58 Compile all zia on windows + launch zia with module
  CMakeLists.txt
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Select.cpp
  SrcModules/Php/src/Module.cpp
  SrcModules/Router/src/Module.cpp
  src/ModuleLoader/DLLoader_Win.hh
  src/Parser/Parser.cpp
  src/zia.cpp
Labels: feat

#59 Module use conf (Network use port into config)
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Network.hh
  src/ModuleLoader/ModuleLoader.cpp
  src/ModuleLoader/ModuleLoader.hh
  src/zia.cpp
Labels: feat

#60 Re enable build in AppVeyor
  .appveyor.yml
Labels: units tests

#61 Zia manage (Part one)
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Network.hh
  SrcModules/Network/src/Select.cpp
  src/Console/Console.cpp
  src/Console/Console.hh
  src/ModuleLoader/DLLoader.hh
  src/ModuleLoader/DLLoader_Win.hh
  src/ModuleLoader/ModuleLoader.cpp
  src/zia.cpp
  src/zia.hh
Labels: feat

#62 netinfoUse(feat): Use netinfo of API (API is use at 100%)
  SrcModules/Network/src/Select.cpp
  SrcModules/Network/src/Socket.cpp
  SrcModules/Network/src/Socket.hh
Labels: enhancement, feat

#63 [UnitTests]: Adding unit tests for code coverage
  .codecov.yml
  get_code_cov.sh
  src/Parser/Parser.cpp
  tests/ConsoleTests.cpp
  tests/HttpParserTests.cpp
  tests/LogTests.cpp
  tests/ModuleLoaderTests.cpp
  tests/ParserTests.cpp
  tests/ProcessTests.cpp
  tests/ZiaTests.cpp
  tests/conf/config.json
Labels: documentation, feat

#72 Zia manage (add reload / set module network)
  src/Console/Console.cpp
  src/zia.cpp
  src/zia.hh
  tests/ConsoleTests.cpp
Labels: feat

#69 DLLoaderCheck(fix): change C cast to Reinterpret_cast in linux dlloader
  src/ModuleLoader/DLLoader.hh
Labels: fix

#71 CheckBoDyInHttpResponse(fix): check if a response contain, or not, a body
  src/HttpParser/HttpParser.cpp
  src/HttpParser/HttpParser.hh
  src/Parser/Parser.cpp
  tests/HttpParserTests.cpp
Labels: fix

#65 Cppcheck
  SrcModules/Network/src/Buffer.cpp
  SrcModules/Network/src/Errors.hpp
  SrcModules/Network/src/HttpParser/HttpParserException.hpp
  SrcModules/Network/src/Network.cpp
  SrcModules/Network/src/Select.cpp
  SrcModules/Network/src/Socket.cpp
  SrcModules/Router/src/Module.cpp
  SrcModules/Router/src/Router.cpp
  conf/config.json
  includes/Log.hpp
  src/Console/Console.cpp
  src/Console/Console.hh
  src/HttpParser/HttpParser.cpp
  src/HttpParser/HttpParserException.hpp
  src/HttpParser/Transform.hpp
  src/ModuleLoader/ModuleLoader.cpp
  src/ModuleLoader/ModuleLoader.hh
  src/Parser/Parser.cpp
  src/Parser/ParserJson.cpp
  src/Parser/ParserJson.hh
  src/Process/Process.cpp
  src/zia.cpp
  src/zia.hh
  tests/ConsoleTests.cpp
  tests/LogTests.cpp
  tests/ParserTests.cpp
  tests/ZiaTests.cpp
Labels: feat, fix, refactor

#76 Requested headers
  src/HttpParser/HttpParser.cpp
Labels: feat

#80 Fix variable argument for the console
  src/Console/Console.cpp
Labels: fix

#66 Move module windows
  .gitignore
  CMakeLists.txt
  SrcModules/Network/CMakeLists.txt
  SrcModules/Php/CMakeLists.txt
  SrcModules/Router/CMakeLists.txt
  build.py
  src/zia.cpp
Labels: Windows, bug

#81 Remove debug / Check error
  SrcModules/Router/src/Router.cpp
  src/ModuleLoader/DLLoader.hh
  src/ModuleLoader/DLLoader_Win.hh
  src/ModuleLoader/ModuleLoader.cpp
  src/Parser/Parser.cpp
  src/zia.cpp
Labels: enhancement, feat, fix

#82 [UnitTests]: Improving unit tests for the Zia Core
  src/Console/Console.cpp
  src/zia.cpp
  tests/ConsoleTests.cpp
  tests/ZiaTests.cpp
Labels: feat
